### ISSUE TITLE
Practica de modelo de negocios

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/practica-de-modelo-de-negocios-equipo-fglr#2]
[PRACTICA MODELO DE NEGOCIOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-modelo-de-negocios-equipo-fglr/files/7342052/PRACTICA.MODELO.DE.NEGOCIOS.pdf)

**Comment by Abraham890** [comment]
Calificacion: 20/20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
